# image manipulation

In [64]:
import cv2
import numpy as np

In [65]:
img = cv2.imread("car.jpg")


In [66]:
cv2.line(img,(0,0),(100,100),(0,0,225),5)

array([[[  0,   0, 225],
        [  0,   0, 225],
        [  0,   0, 225],
        ...,
        [238, 233, 232],
        [239, 234, 233],
        [239, 234, 233]],

       [[  0,   0, 225],
        [  0,   0, 225],
        [  0,   0, 225],
        ...,
        [239, 234, 233],
        [239, 234, 233],
        [239, 234, 233]],

       [[  0,   0, 225],
        [  0,   0, 225],
        [  0,   0, 225],
        ...,
        [239, 234, 233],
        [239, 234, 233],
        [239, 234, 233]],

       ...,

       [[102,  86,  80],
        [102,  86,  80],
        [102,  86,  80],
        ...,
        [128, 109, 102],
        [127, 108, 101],
        [126, 107, 100]],

       [[101,  85,  79],
        [101,  85,  79],
        [102,  86,  80],
        ...,
        [129, 110, 103],
        [128, 109, 102],
        [126, 107, 100]],

       [[100,  84,  78],
        [100,  84,  78],
        [101,  85,  79],
        ...,
        [128, 109, 102],
        [126, 107, 100],
        [125, 106,  99]]

In [67]:
pt1 = (0, 0)
pt2 = (100, 100)
color = (0, 0, 255)
thickness = 5
cv2.rectangle(img, pt1, pt2, color, thickness)

array([[[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [238, 233, 232],
        [239, 234, 233],
        [239, 234, 233]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [239, 234, 233],
        [239, 234, 233],
        [239, 234, 233]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [239, 234, 233],
        [239, 234, 233],
        [239, 234, 233]],

       ...,

       [[102,  86,  80],
        [102,  86,  80],
        [102,  86,  80],
        ...,
        [128, 109, 102],
        [127, 108, 101],
        [126, 107, 100]],

       [[101,  85,  79],
        [101,  85,  79],
        [102,  86,  80],
        ...,
        [129, 110, 103],
        [128, 109, 102],
        [126, 107, 100]],

       [[100,  84,  78],
        [100,  84,  78],
        [101,  85,  79],
        ...,
        [128, 109, 102],
        [126, 107, 100],
        [125, 106,  99]]

In [68]:
center = (100, 100)
radius = 50
color = (0, 255, 0) 
thickness = 3
cv2.circle(img, center, radius, color, thickness)
center1 = (300, 300)
radius1 = 50
color1 = (0, 0, 255) 
thickness1 = 5
cv2.circle(img, center1, radius1, color1, thickness1)

array([[[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [238, 233, 232],
        [239, 234, 233],
        [239, 234, 233]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [239, 234, 233],
        [239, 234, 233],
        [239, 234, 233]],

       [[  0,   0, 255],
        [  0,   0, 255],
        [  0,   0, 255],
        ...,
        [239, 234, 233],
        [239, 234, 233],
        [239, 234, 233]],

       ...,

       [[102,  86,  80],
        [102,  86,  80],
        [102,  86,  80],
        ...,
        [128, 109, 102],
        [127, 108, 101],
        [126, 107, 100]],

       [[101,  85,  79],
        [101,  85,  79],
        [102,  86,  80],
        ...,
        [129, 110, 103],
        [128, 109, 102],
        [126, 107, 100]],

       [[100,  84,  78],
        [100,  84,  78],
        [101,  85,  79],
        ...,
        [128, 109, 102],
        [126, 107, 100],
        [125, 106,  99]]

In [69]:
cv2.imshow("image",img)
cv2.waitKey(0)
cv2.destroyAllWindows()